### ISSUE TITLE
Dimention too large

### ISSUE THREAD

**Issue by minhthien2016** [marmotghost/tikz-3dtools#11] opened 2023-05-14 23:38 UTC
I am trying to answer [this quesion](https://tex.stackexchange.com/questions/685595/how-can-i-construct-the-point-s-of-this-tetrahedron-and-draw-a-sphere-passing-th/685642#685642) with this code
`
\documentclass[tikz,border=3mm]{standalone}
\usetikzlibrary{calc,decorations.pathreplacing,3dtools} % https://github.com/marmotghost/tikz-3dtools
\begin{document}
\begin{tikzpicture}[line cap=round,line join=round,c/.style={circle,fill,inner sep=1pt},
	declare function={lAB=15;lAC=14;lBC=13;lAD=16;lBD=17;lCD=18;}]
	% ^^^ the lengths of the tetrahedron	
	\begin{scope}[3d/install view={phi=60,psi=0,theta=70}]
		% construct a triangle of three vertices in the xy plane 
		% using the cosine law	
		\pgfmathsetmacro{\mytheta}{acos(-1*(lBC*lBC-lAC*lAC-lAB*lAB)/(2*lAB*lAC))}	
		\path (0,0,0) coordinate (A)
		(lAB,0,0) coordinate (B)
		({lAC*cos(\mytheta)},{lAC*sin(\mytheta)},0) coordinate (C);
\path[overlay,3d/aux keys/i1=D,3d/aux keys/i2=D',
		3d/intersection of three spheres={rA=lAD,rB=lBD,rC=lCD}]; 
\path[3d/circumsphere center={A={(A)},B={(B)},C={(C)},D={(D)}}]
coordinate (I); 
\pgfmathsetmacro{\myR}{sqrt(TD("(I)-(A)o(I)-(A)"))} ;
\path[3d/circumcircle center={A={(A)},B={(B)},C={(C)}}] coordinate (G);

\draw[3d/screen coords] (I) circle[radius=\myR]; 
\path  pic{3d/circle on sphere={R=\myR,C={(I)}, P={(G)}}};
		\path foreach \p/\g in {A/180,B/-90,C/0,D/90,G/-90,I/0}{(\p)node[c]{}+(\g:2.5mm) node{$\p$}};
			\draw[3d/hidden] (A) -- (C) (D) -- (A) (D) -- (G)  (D) -- (B) (D) --(C) (A) -- (B) -- (C);
	\end{scope}
\end{tikzpicture}
\end{document}
`
I got Dimention too large. How can I avoid it?

**Comment by marmotghost** [comment] 2023-05-23 15:59
I already get an error from 
```
\pgfmathsetmacro{\mytheta}{acos(-1*(lBClBC-lAClAC-lABlAB)/(2lABlAC))}
```
since `lBClBC` is not defined. This may be due to the fact that the code is not correctly formatted (you need three backticks, not one), but since I do not precisely know what you want to do I cannot reproduce the issue. Please consider formatting the code and trying it out first.

**Comment by marmotghost** [comment] 2023-05-23 17:23
I tried to find out what the correct code might be, and could reproduce an error. This error is fixed in the most recent update. 

As I said, in the future it would be great if you could look at the codes that you post in order to avoid misunderstandings. 

On a different note, I took the liberty to slightly shorten and improve your nice code https://tex.stackexchange.com/questions/684305/can-i-general-this-code-to-draw-a-regular-polyhedron in https://github.com/marmotghost/tikz-3dtools/issues/10.

**Comment by minhthien2016** [comment] 2023-05-24 01:44
Thank you very much. The code runs, now.

**Closed** 2023-05-24 02:02 UTC
